import { NextRequest, NextResponse } from "next/server";
import { requireAuth, handleApiError } from "@/lib/auth/guard";

export interface AIAnalysisRequest {
  channelTitle?: string;
  views: number;
  viewsDelta?: string | null;
  watchTimeHours: number;
  avgDurationSec: number;
  netSubscribers: number;
  subscribersGained: number;
  subscribersLost: number;
  likes: number;
  comments: number;
  shares: number;
  engagementRate: number;
  totalSubscribersLifetime?: string | null;
  lifetimeViews?: string | null;
}

export async function POST(req: NextRequest) {
  try {
    await requireAuth();

    const apiKey = process.env.GEMINI_API_KEY || process.env.AI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY is not configured in .env file." },
        { status: 500 }
      );
    }

    const data = (await req.json()) as AIAnalysisRequest;

    const systemPrompt = `Anda adalah "Plottershub AI Growth Consultant & YouTube Algorithm Specialist".
Tugas Anda: Menganalisis metrik data YouTube creator dan memberikan Hasil Analisa, Kesimpulan, Saran Strategis Kedepan, dan Taktik Konkret Menaikkan Views.

Berikan analisis dalam BAHASA INDONESIA yang lugas, profesional, cerdas, tajam, dan langsung dapat dieksekusi.
Format output WAJIB HANYA berupa JSON valid murni (tanpa tanda kutip markdown \`\`\`json atau teks pengantar apapun) dengan struktur persis seperti ini:

{
  "summaryHeadline": "Ringkasan 1 kalimat tajam tentang status pertumbuhan channel saat ini",
  "analysis": [
    {
      "title": "Judul poin analisa",
      "detail": "Penjelasan detail berbasis angka metrik",
      "highlight": "Highlight metrik penting"
    }
  ],
  "conclusion": [
    {
      "title": "Kekuatan / Hambatan utama",
      "detail": "Penjelasan kesimpulan",
      "type": "strength"
    },
    {
      "title": "Kekuatan / Hambatan utama",
      "detail": "Penjelasan kesimpulan",
      "type": "weakness"
    }
  ],
  "roadmap": [
    {
      "step": "Langkah 1",
      "title": "Nama aksi strategis",
      "description": "Panduan implementasi detail untuk kreator"
    }
  ],
  "tactics": [
    {
      "title": "Nama taktik algoritma",
      "formula": "Rumus atau aturan praktis",
      "explanation": "Cara eksekusi di video selanjutnya agar views meledak"
    }
  ]
}`;

    const userPrompt = `Berikut adalah data metrik channel YouTube kreator:
- Channel: ${data.channelTitle || "Plottershub"}
- Total Views Periode: ${data.views.toLocaleString()} (Pertumbuhan: ${data.viewsDelta || "Tinggi"})
- Watch Time: ${data.watchTimeHours.toLocaleString()} Jam
- Rata-rata Durasi Tonton (Avg Duration): ${data.avgDurationSec} Detik
- Net Subscriber Baru: +${data.netSubscribers.toLocaleString()} (+${data.subscribersGained} bertambah / -${data.subscribersLost} unsubscribed)
- Likes: ${data.likes.toLocaleString()}
- Comments: ${data.comments.toLocaleString()}
- Shares: ${data.shares.toLocaleString()}
- Engagement Rate: ${data.engagementRate.toFixed(2)}%
- Total Subscribers Saat Ini: ${data.totalSubscribersLifetime || "Belum terdata"}
- Total Lifetime Views: ${data.lifetimeViews || "Belum terdata"}

Berdasarkan angka-angka di atas, buatlah analisis mendalam, kesimpulan yang tajam, saran masa depan, dan trik menaikkan views secara eksponensial. Berikan output JSON murni sekarang:`;

    const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;

    const response = await fetch(geminiUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [
          {
            role: "user",
            parts: [{ text: `${systemPrompt}\n\n${userPrompt}` }],
          },
        ],
        generationConfig: {
          temperature: 0.7,
          responseMimeType: "application/json",
        },
      }),
    });

    if (!response.ok) {
      const errBody = await response.text();
      console.error("Gemini API Error:", response.status, errBody);
      return NextResponse.json(
        { error: `Gemini API returned ${response.status}: ${errBody}` },
        { status: response.status }
      );
    }

    const resultData = await response.json();
    const rawText = resultData.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!rawText) {
      return NextResponse.json(
        { error: "No response text generated by Gemini." },
        { status: 500 }
      );
    }

    let parsedJson;
    try {
      parsedJson = JSON.parse(rawText);
    } catch {
      // Clean possible markdown code fences if any
      const cleaned = rawText.replace(/```json/gi, "").replace(/```/g, "").trim();
      parsedJson = JSON.parse(cleaned);
    }

    return NextResponse.json({
      success: true,
      data: parsedJson,
      generatedAt: new Date().toISOString(),
      model: "gemini-2.5-flash",
    });
  } catch (error) {
    return handleApiError(error);
  }
}
